#!/usr/bin/env python3
"""Materialise the curated skills into a project's `.claude/skills/`.

Skills committed under `.claude/skills/` load automatically for anyone who clones
the repository — no marketplace, no per-developer install step. This script
fetches each curated skill from its own upstream repository at the pinned commit
in `catalog.json` and writes it there.

    python3 scripts/install-skills.py --project /path/to/repo            # core set
    python3 scripts/install-skills.py --project /path/to/repo --full     # everything
    python3 scripts/install-skills.py --project /path/to/repo --list     # dry run

Re-running updates in place. A manifest is written to
`.claude/skills/.dev-skills.json` recording exactly which commit each skill came
from, so the result is reproducible and re-checkable.

Requires: git, and network access to github.com.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog.json"
ROUTER = ROOT / "plugins" / "dev-lifecycle" / "skills" / "development-lifecycle"


# MIT and Apache-2.0 both require the licence and copyright notice to travel with
# redistributed copies. Writing skills into a project is redistribution, so the
# installer carries the notices rather than leaving that to the user.
LICENSE_CANDIDATES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING")


def fetch_license(repo: str, ref: str) -> tuple[str, str] | None:
    """Return (filename, text) of the upstream licence, or None if not found."""
    for name in LICENSE_CANDIDATES:
        url = f"https://raw.githubusercontent.com/{repo}/{ref}/{name}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "dev-skills-install"})
            with urllib.request.urlopen(req, timeout=30) as r:
                if r.status == 200:
                    return name, r.read().decode("utf-8", "replace")
        except urllib.error.HTTPError:
            continue
        except Exception:
            return None
    return None


def write_attribution(skills_dir: Path, manifest: dict, sources: dict) -> int:
    """Write licence texts and an attribution index next to the skills."""
    lic_dir = skills_dir / "licenses"
    lic_dir.mkdir(exist_ok=True)

    used = {}
    for meta in manifest["skills"].values():
        if meta["repo"] != "yuusakuri/dev-skills":
            used.setdefault(meta["repo"], meta["ref"])

    lines = [
        "# Attribution",
        "",
        "The skills in this directory were copied from the repositories below at the",
        "commits shown. They remain under their original licences; the full texts are in",
        "`licenses/`. This file is generated by `dev-skills`' installer — do not edit it",
        "by hand.",
        "",
        "| Skill | Upstream | Commit | Licence |",
        "|---|---|---|---|",
    ]
    for name in sorted(manifest["skills"]):
        m = manifest["skills"][name]
        ref = "—" if m["ref"] == "local" else f"`{m['ref'][:8]}`"
        lines.append(f"| `{name}` | {m['repo']} | {ref} | {m['license']} |")

    missing = 0
    lines += ["", "## Licence texts", ""]
    for repo, ref in sorted(used.items()):
        slug = repo.replace("/", "__")
        got = fetch_license(repo, ref)
        if got:
            fname, text = got
            (lic_dir / f"{slug}.{fname}").write_text(text, encoding="utf-8")
            lines.append(f"- **{repo}** — [`licenses/{slug}.{fname}`](licenses/{slug}.{fname})")
        else:
            missing += 1
            lines.append(
                f"- **{repo}** — licence file not retrieved; see "
                f"<https://github.com/{repo}> before redistributing"
            )
    lines.append("")
    (skills_dir / "ATTRIBUTION.md").write_text("\n".join(lines), encoding="utf-8")
    return missing


def run(cmd: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def fetch_paths(repo: str, ref: str, paths: list[str], dest: Path) -> None:
    """Sparse-fetch only `paths` from `repo` at `ref` into `dest`.

    A full clone of these repositories is large and unnecessary: some hold
    hundreds of skills. Sparse checkout at a pinned SHA keeps this to the files
    actually curated.
    """
    url = f"https://github.com/{repo}"
    for cmd in (
        ["git", "init", "-q", "."],
        ["git", "remote", "add", "origin", url],
        ["git", "sparse-checkout", "init", "--cone"],
        ["git", "sparse-checkout", "set", *paths],
        ["git", "fetch", "--depth", "1", "-q", "origin", ref],
        ["git", "checkout", "-q", "FETCH_HEAD"],
    ):
        r = run(cmd, cwd=dest)
        if r.returncode != 0:
            raise RuntimeError(
                f"{repo}@{ref[:8]}: `{' '.join(cmd[:3])}` failed — "
                f"{(r.stderr or r.stdout).strip().splitlines()[-1] if (r.stderr or r.stdout).strip() else 'no output'}"
            )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", required=True, help="target repository root")
    ap.add_argument("--full", action="store_true",
                    help="install every curated skill (default: the core set)")
    ap.add_argument("--skills", help="comma-separated skill names, overrides --full")
    ap.add_argument("--list", action="store_true", help="show what would be installed")
    args = ap.parse_args()

    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    sources = catalog["sources"]

    wanted = [s.strip() for s in args.skills.split(",")] if args.skills else None
    selected = []
    for phase in catalog["phases"]:
        for e in phase["entries"]:
            if wanted is not None:
                if e["skill"] in wanted:
                    selected.append((phase["id"], e))
            elif args.full or e.get("core"):
                selected.append((phase["id"], e))

    if wanted:
        missing = set(wanted) - {e["skill"] for _, e in selected}
        if missing:
            print(f"error: not in the catalog: {', '.join(sorted(missing))}", file=sys.stderr)
            return 1

    if args.list:
        print(f"{len(selected)} skills ({'full' if args.full or wanted else 'core'} set)"
              f" + development-lifecycle router\n")
        for pid, e in selected:
            print(f"  [{pid:<16}] {e['skill']:<32} {sources[e['source']]['repo']}")
        return 0

    project = Path(args.project).expanduser().resolve()
    if not project.is_dir():
        print(f"error: {project} is not a directory", file=sys.stderr)
        return 1
    skills_dir = project / ".claude" / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    # Group by source so each upstream is fetched once, not once per skill.
    by_source: dict[str, list[dict]] = {}
    for _, e in selected:
        by_source.setdefault(e["source"], []).append(e)

    manifest = {
        "generated_by": "yuusakuri/dev-skills scripts/install-skills.py",
        "profile": "full" if args.full else ("custom" if wanted else "core"),
        "skills": {},
    }
    installed = failed = 0

    for key, entries in by_source.items():
        src = sources[key]
        print(f"{src['repo']} @ {src['ref'][:8]} ({len(entries)} skills)")
        with tempfile.TemporaryDirectory() as tmp:
            tmpdir = Path(tmp)
            try:
                fetch_paths(src["repo"], src["ref"], [e["path"] for e in entries], tmpdir)
            except RuntimeError as exc:
                print(f"  FAILED: {exc}", file=sys.stderr)
                failed += len(entries)
                continue

            for e in entries:
                source_dir = tmpdir / e["path"]
                if not (source_dir / "SKILL.md").is_file():
                    print(f"  FAILED {e['skill']}: no SKILL.md at {e['path']}", file=sys.stderr)
                    failed += 1
                    continue
                target = skills_dir / e["skill"]
                if target.exists():
                    shutil.rmtree(target)
                shutil.copytree(source_dir, target)
                manifest["skills"][e["skill"]] = {
                    "repo": src["repo"], "ref": src["ref"],
                    "path": e["path"], "license": src["license"],
                }
                print(f"  ok {e['skill']}")
                installed += 1

    # The router is this repository's own skill, so copy it directly.
    target = skills_dir / "development-lifecycle"
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(ROUTER, target)
    manifest["skills"]["development-lifecycle"] = {
        "repo": "yuusakuri/dev-skills", "ref": "local",
        "path": "plugins/dev-lifecycle/skills/development-lifecycle", "license": "MIT",
    }
    installed += 1
    print("yuusakuri/dev-skills\n  ok development-lifecycle")

    (skills_dir / ".dev-skills.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    missing_licenses = write_attribution(skills_dir, manifest, sources)
    print("\nwrote ATTRIBUTION.md and licenses/ "
          "(copying these skills into your repo is redistribution)")
    if missing_licenses:
        print(f"  warning: {missing_licenses} licence file(s) could not be fetched — "
              "check them before publishing", file=sys.stderr)

    print(f"\n{installed} skills installed to {skills_dir}")
    if failed:
        print(f"{failed} failed", file=sys.stderr)
    print("\nNext:")
    print(f"  cd {project}")
    print("  git add .claude/skills && git commit -m 'Add curated agent skills'")
    print("\nAnyone who clones the repository now gets these automatically —")
    print("no marketplace, no per-developer install step.")
    return 1 if failed else 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrokenPipeError:
        try:
            sys.stdout.close()
        finally:
            sys.exit(0)
